import { CATEGORY_LABELS, escapeHtml, safeUrl } from "./reports.js";

export const createAllState = () => ({ days: 7, cat: "all", showAll: false });

export async function renderAllDynamics({ dataApi, state }) {
  const dates = await dataApi.allManifest(); if (!dates.length) return '<div class="empty" role="status">暂无全部动态数据</div>';
  const shown = dates.slice(0, state.days); const days = await Promise.all(shown.map(async (date) => [date, await dataApi.allDay(date)])); const cats = ["all", ...Object.keys(CATEGORY_LABELS)];
  return `<section><h1>全部动态</h1><div class="tabs">${cats.map((cat) => `<button type="button" class="tab ${state.cat === cat ? "on" : ""}" data-all-action="set-cat" data-value="${cat}">${cat === "all" ? "全部" : CATEGORY_LABELS[cat]}</button>`).join("")}<button type="button" class="tab ${state.showAll ? "on" : ""}" data-all-action="show-all">${state.showAll ? "✓ 含低分/未评分" : "显示全部（含低分/未评分）"}</button></div>${days.map(([date, data]) => { const min = Number(data?.min_score ?? 40); const all = (data?.items || []).filter((item) => state.cat === "all" || item.c === state.cat); const rows = all.filter((item) => state.showAll || (Number.isFinite(item.score) && item.score >= min)); const hidden = all.length - rows.length; return `<section><h2 class="feed-day">${escapeHtml(date)}</h2>${hidden ? `<p class="hidden-bar">已隐藏 ${hidden} 条低分/未评分</p>` : ""}<div class="more-list">${rows.map((item) => { const url = item.url || item.u; return `<article class="row"><span class="tag">${escapeHtml(CATEGORY_LABELS[item.c] || item.c)}</span><strong>${escapeHtml(item.title || item.t)}</strong><span>${escapeHtml(item.summary || item.sn || "")}</span>${Number.isFinite(item.score) ? `<span>${item.score} 分</span>` : ""}${url ? `<a href="${safeUrl(url)}" target="_blank" rel="noopener noreferrer">原文</a>` : ""}</article>`; }).join("") || '<p class="section-empty">暂无动态</p>'}</div></section>`; }).join("")}${state.days < dates.length ? '<button type="button" class="toggle-more" data-all-action="more">加载更早 ▼</button>' : ""}</section>`;
}
